### ISSUE TITLE
UX -  Disable spell checking for ieml strings

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#13]

**Comment by maxtheman33** [comment]
no longer manifests itself. Confirmation and test case is needed.

**Comment by casuistry** [comment]
When editing, ieml field is read-only, so I guess the spell check does not kick-in. When creating a new entry, for example o.wa.-f.-' you will see the spell check complaining.

This issue is not urgent/important. If it takes too much time, just comment on what has been tried/researched and we will park it.
