### ISSUE TITLE
UX - turn on validation on dirty

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#15]

**Comment by casuistry** [comment]
Check out "Select" Material demo, scroll down to "Validation"

**Comment by maxtheman33** [comment]
need a refresher, what was our use case here?

**Comment by casuistry** [comment]
We are using the same html code for two use cases: creating a new entry and editing an existing entry.  When creating a new entry, the situation is simple: any ieml, french or english strings have to be unique, i.e. not in the database. Validation is turned on by default. In the edit case, those three strings will obviously already be in the database so we don't want validation unless something has changed (dirty). I saw something about 'dirty' flag in  "Select" Material demo, scroll down to "Validation".

This is not urgent but important.

**Comment by maxtheman33** [comment]
done
