### ISSUE TITLE
Retrieve layer and "class" of ieml string

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#18]
When creating a new entry, the layer and the "class" of the ieml string is required. This info is available on java side, we need to be able to get it to the browser

**Comment by maxtheman33** [comment]
how to use API to obtain this after Token n = parser.parse(iemltext);?

**Comment by casuistry** [comment]
For layer, Token has a public layer variable 
(i.e, for Token n = parser.parse(iemltext); what_we_want = n.layer)

For "class" (example from JsonGenerator.java):

Token n = parser.parse(parts[0].trim());  
int ieml_class = n.GetTokenClass();

**Comment by casuistry** [comment]
This one is important and urgent ;-)

**Comment by maxtheman33** [comment]
done  i.e {"level":3,"class":2,"success":true} for  o.wa.-f.-'
