### ISSUE TITLE
UI - display the returned tree structure 

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#26]
Display the tree structure in the browser. I heard of d3.js, perhaps there are other libraries to consider. 

Requirements for the library: 
- trees can be large and not fitting on the available screen space. 
- layout of the tree (if we can avoid calculating the layout ourselves, that would be great). I used repulsion and springs type of a layout algorithm before.
- we need to be allowed to interact with the nodes and possibly links at some point, as well as do some basic filtering.

**Comment by casuistry** [comment]
we could consider a tabbed page which holds the table and the tree on separate tabs.

**Comment by maxtheman33** [comment]
simple tree is implemented on d3 branch
