### ISSUE TITLE
UI - Tree, order of children

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#30]
The tree shows the relation between parent and children. In the case of  ' \* ' there are only 3 children. It appears that depending on which input is selected, the order of those three children (vertically) changes. It should always be the same and alway show the first child on the top, second child in the middle, and last child at the bottom.

**Comment by maxtheman33** [comment]
to make sure I understood in correctly: in one case you expand '_' and there is ABC order, then looking at another ieml with '_' component it might say BCA. If that is the case, we need to make sure that they are coming out of the parser in the consistent order. Give me few particular iemls and I will compare order out of the parser.

**Comment by casuistry** [comment]
o.wa.-   should be :

o [top]
wa [middle]
EEE [bottom]

right now it is:

EEE
o
wa

n.j.-

should be
n [top]
j [middle]
EEE [bottom]

right now it is

EEE
j
n

**Comment by maxtheman33** [comment]
with  tree sort removed it looks as required so far. close?
