### ISSUE TITLE
Update not fully implemented

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#32]
Finish implementing 'update' functionality. For example, for any input, if 'paradigm' box is toggled, the result is not saved ("502 OK" appears) when 'save' button is clicked

**Comment by maxtheman33** [comment]
the behaviour is different on local dev and prod. I'll look into prod later once local dev is fixed. What happens right now is that when you touch paradigm, instead of editing the item, new item is created. I have more than one already with same ieml. I do not see an 'update' call being made anywhere so what is the correct approach for this ?

**Comment by maxtheman33** [comment]
that is what I get on my local setup after setting paradigm to 1 and saving it:

> db.terms.find({IEML:"t.i.-s.i.-'"})
> { "_id" : ObjectId("55d489719a475d79aa74e4c1"), "IEML" : "t.i.-s.i.-'", "FR" : "
> véhicule", "EN" : "vehicle", "PARADIGM" : "0", "LAYER" : "3", "CLASS" : "4" }
> { "_id" : ObjectId("5601d1def32b49c00aa751b4"), "IEML" : "t.i.-s.i.-'", "FR" : "
> véhicule", "EN" : "vehicle", "PARADIGM" : "1", "LAYER" : "3", "CLASS" : "4" }
> { "_id" : ObjectId("5601d20cf32b49c00aa751b5"), "IEML" : "t.i.-s.i.-'", "FR" : "
> véhicule", "EN" : "vehicle", "PARADIGM" : "1", "LAYER" : "3", "CLASS" : "4" }
> { "_id" : ObjectId("5601d2e57768f1681a50c8a3"), "IEML" : "t.i.-s.i.-'", "FR" : "
> véhicule", "EN" : "vehicle", "PARADIGM" : "1", "LAYER" : "3", "CLASS" : "4" }
> { "_id" : ObjectId("5601d33f7768f1681a50c8a4"), "IEML" : "t.i.-s.i.-'", "FR" : "
> véhicule", "EN" : "vehicle", "PARADIGM" : "1", "LAYER" : "3", "CLASS" : "4" }

**Comment by maxtheman33** [comment]
I suggest the following:
- instead of adding new api call to update we still can use newieml call but:
- if id is passed and find returns an element call update, otherwise create new element

**Comment by casuistry** [comment]
verified
