### ISSUE TITLE
Create and update - space not handled

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#33]
When editing french or english variables, " " (space) is not allowed. It should be possible to enter space as it is a valid character (as well as in the ieml field, since it will be parsed out). French and english fields must preserve spaces

**Comment by maxtheman33** [comment]
A - check local and update issue
M - check on cloud (angular and material versions)

**Comment by casuistry** [comment]
On my box:
  local - allows spaces
  cloud - does not

package and bower json files are the same for local and cloud

**Comment by maxtheman33** [comment]
good : it is working now
bad: could not quickly find a way how to execute 'bower list' remotely. I sshed, found location of the repo but permissionb issue would not allow me to run 'info' to compare versions.
I did update again and it seem to work now.
Please verify and close.

**Comment by casuistry** [comment]
works ;-)
