### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#38]
1) enable auth on 'delete'

What about 'modify'?

**Comment by maxtheman33** [comment]
Sgo                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: casuistrySent: Monday, October 12, 2015 6:09 PMTo: casuistry/iemlReply To: casuistry/iemlSubject: [ieml] Authentication (#38)1) enable auth on 'delete'

What about 'modify'?

—Reply to this email directly or view it on GitHub.

**Comment by maxtheman33** [comment]
all crud is done

**Comment by casuistry** [comment]
verified
