### ISSUE TITLE
Crud - modify action changes order in list

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#39]
2) add listieml sort because right now it seems to be modification date and item on top will go to the end of the list once you modify it

**Comment by maxtheman33** [comment]
need more details here. If we want to have few sort options,server roundtrip will be required unless we use some poor man sort on the array

**Comment by maxtheman33** [comment]
Array.sort() might do . What do we sort on and should we have different sort options?

**Comment by casuistry** [comment]
We'll add a new filter, ieml, french or english. Fr/En will sort according to alphabetical order, ieml will sort according to ieml order (TBD). For now Ieml order does not have to do anything.

**Comment by casuistry** [comment]
IEML order implemented.
