### ISSUE TITLE
Table - UI - french and english

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#44]
ieml portion: use smaller font than french and english, not editable
french and english portion: editable.

If no fr/en portion then new entry is created in DB
Else if fr/en portion is modified, entry is updated in DB

**Comment by casuistry** [comment]
fr/en portion might be very long. only max 25 chars should be displayed, full entry visible in the tooltip.

**Comment by casuistry** [comment]
Table cells should provide input for FR and EN

**Comment by maxtheman33** [comment]
how about that we just pop 'add ieml' screen to reuse same workflow?

On Thu, Oct 22, 2015 at 9:56 PM, casuistry notifications@github.com wrote:

> Assigned #44 https://github.com/casuistry/ieml/issues/44 to @maxtheman33
> https://github.com/maxtheman33.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/44#event-443332713.

## 

Слава Украине! Glory to Ukraine!

**Comment by casuistry** [comment]
Or when clicked, present user with an entry form where to enter FR/EN but not ieml

**Comment by casuistry** [comment]
you beat me to it

**Comment by maxtheman33** [comment]
do we have a way to tell that the cell in the table already has a record in
ieml table in this case we can make it uneditable for now or  may pop up
edit screen.

On Thu, Oct 22, 2015 at 10:00 PM, casuistry notifications@github.com
wrote:

> you beat me to it
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/44#issuecomment-150410587.

## 

Слава Украине! Glory to Ukraine!

**Comment by casuistry** [comment]
Good point. We need to fill the cells of tables with FR/EN if the corresponding ieml exists in DB. When this is done, we know which cells creates new and which updates entries. Tooltips will be needed here.

This task is very broad in scope...

**Comment by casuistry** [comment]
To get FR/EN to display on the table we have these options:
- get java cloud to make calls to DB and fill out the JSON before returning
  to the browser,
- browser makes calls (or cross-ckecks agains the list it already has) to
  DB when JSON is returned from java cloud and it updates JSON
- leave as is now but trigger an async call to fill out cells

Any other options?

**Comment by maxtheman33** [comment]
```
                                                                                  I was thinking second                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: casuistrySent: Saturday, October 24, 2015 10:13 AMTo: casuistry/iemlReply To: casuistry/iemlCc: maxtheman33Subject: Re: [ieml] Table - UI - french and english (#44)To get FR/EN to display on the table we have these options:
```
- get java cloud to make calls to DB and fill out the JSON before returning
  to the browser,
- browser makes calls (or cross-ckecks agains the list it already has) to
  DB when JSON is returned from java cloud and it updates JSON
- leave as is now but trigger an async call to fill out cells

Any other options?

On Thu, Oct 22, 2015 at 10:03 PM, maxtheman33 notifications@github.com
wrote:

> do we have a way to tell that the cell in the table already has a record in
> ieml table in this case we can make it uneditable for now or may pop up
> edit screen.
> 
> On Thu, Oct 22, 2015 at 10:00 PM, casuistry notifications@github.com
> wrote:
> 
> > you beat me to it
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/casuistry/ieml/issues/44#issuecomment-150410587.
> 
> ## 
> 
> Слава Украине! Glory to Ukraine!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/44#issuecomment-150410906.

—Reply to this email directly or view it on GitHub.

**Comment by casuistry** [comment]
Ok, I'll see if I can check against the list with a filter

**Comment by maxtheman33** [comment]
I do not think that original ieml data is being modified somehow

On Sat, Oct 24, 2015 at 10:55 AM, casuistry notifications@github.com
wrote:

> Ok, I'll see if I can check against the list with a filter
> 
> On Sat, Oct 24, 2015 at 10:48 AM, maxtheman33 notifications@github.com
> wrote:
> 
> > I was thinking second Sent from my BlackBerry 10 smartphone. From:
> > casuistrySent: Saturday, October 24, 2015 10:13 AMTo: casuistry/iemlReply
> > To: casuistry/iemlCc: maxtheman33Subject: Re: [ieml] Table - UI - french
> > and english (#44)To get FR/EN to display on the table we have these
> > options:
> > - get java cloud to make calls to DB and fill out the JSON before
> >   returning
> >   to the browser,
> > - browser makes calls (or cross-ckecks agains the list it already has) to
> >   DB when JSON is returned from java cloud and it updates JSON
> > - leave as is now but trigger an async call to fill out cells
> > 
> > Any other options?
> > 
> > On Thu, Oct 22, 2015 at 10:03 PM, maxtheman33 notifications@github.com
> > wrote:
> > 
> > > do we have a way to tell that the cell in the table already has a
> > > record
> > > in
> > > ieml table in this case we can make it uneditable for now or may pop up
> > > edit screen.
> > > 
> > > On Thu, Oct 22, 2015 at 10:00 PM, casuistry notifications@github.com
> > > wrote:
> > > 
> > > > you beat me to it
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/casuistry/ieml/issues/44#issuecomment-150410587
> > > > .
> > > 
> > > ## 
> > > 
> > > Слава Украине! Glory to Ukraine!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/casuistry/ieml/issues/44#issuecomment-150410906.
> > 
> > —Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/casuistry/ieml/issues/44#issuecomment-150823933.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/44#issuecomment-150824207.

## 

Слава Украине! Glory to Ukraine!

**Comment by casuistry** [comment]
what do you mean?

**Comment by maxtheman33** [comment]
that ieml variable we store full list of IEML will always have full list
even if it is displayed as filtered

On Sat, Oct 24, 2015 at 11:13 AM, casuistry notifications@github.com
wrote:

> what do you mean?
> 
> On Sat, Oct 24, 2015 at 11:09 AM, maxtheman33 notifications@github.com
> 
> wrote:
> 
> > I do not think that original ieml data is being modified somehow
> > 
> > On Sat, Oct 24, 2015 at 10:55 AM, casuistry notifications@github.com
> > wrote:
> > 
> > > Ok, I'll see if I can check against the list with a filter
> > > 
> > > On Sat, Oct 24, 2015 at 10:48 AM, maxtheman33 <
> > > notifications@github.com>
> > > wrote:
> > > 
> > > > I was thinking second Sent from my BlackBerry 10 smartphone. From:
> > > > casuistrySent: Saturday, October 24, 2015 10:13 AMTo:
> > > > casuistry/iemlReply
> > > > To: casuistry/iemlCc: maxtheman33Subject: Re: [ieml] Table - UI -
> > > > french
> > > > and english (#44)To get FR/EN to display on the table we have these
> > > > options:
> > > > - get java cloud to make calls to DB and fill out the JSON before
> > > >   returning
> > > >   to the browser,
> > > > - browser makes calls (or cross-ckecks agains the list it already
> > > >   has)
> > > >   to
> > > >   DB when JSON is returned from java cloud and it updates JSON
> > > > - leave as is now but trigger an async call to fill out cells
> > > > 
> > > > Any other options?
> > > > 
> > > > On Thu, Oct 22, 2015 at 10:03 PM, maxtheman33 <
> > > > notifications@github.com>
> > > > wrote:
> > > > 
> > > > > do we have a way to tell that the cell in the table already has a
> > > > > record
> > > > > in
> > > > > ieml table in this case we can make it uneditable for now or may
> > > > > pop
> > > > > up
> > > > > edit screen.
> > > > > 
> > > > > On Thu, Oct 22, 2015 at 10:00 PM, casuistry <
> > > > > notifications@github.com>
> > > > > wrote:
> > > > > 
> > > > > > you beat me to it
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > > > > https://github.com/casuistry/ieml/issues/44#issuecomment-150410587
> > > > > > .
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Слава Украине! Glory to Ukraine!
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > > > https://github.com/casuistry/ieml/issues/44#issuecomment-150410906
> > > > > .
> > > > 
> > > > —Reply to this email directly or view it on GitHub.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/casuistry/ieml/issues/44#issuecomment-150823933
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/casuistry/ieml/issues/44#issuecomment-150824207.
> > 
> > ## 
> > 
> > Слава Украине! Glory to Ukraine!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/casuistry/ieml/issues/44#issuecomment-150825624.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/44#issuecomment-150825808.

## 

Слава Украине! Glory to Ukraine!

**Comment by casuistry** [comment]
That is good: for each ieml returned from the table generation, it will
have to be cross-checked against that list.

**Comment by maxtheman33** [comment]
yes. Are you working on it?

On Sat, Oct 24, 2015 at 11:21 AM, casuistry notifications@github.com
wrote:

> That is good: for each ieml returned from the table generation, it will
> have to be cross-checked against that list.
> 
> On Sat, Oct 24, 2015 at 11:16 AM, maxtheman33 notifications@github.com
> wrote:
> 
> > that ieml variable we store full list of IEML will always have full list
> > even if it is displayed as filtered
> > 
> > On Sat, Oct 24, 2015 at 11:13 AM, casuistry notifications@github.com
> > wrote:
> > 
> > > what do you mean?
> > > 
> > > On Sat, Oct 24, 2015 at 11:09 AM, maxtheman33 <
> > > notifications@github.com>
> > > 
> > > wrote:
> > > 
> > > > I do not think that original ieml data is being modified somehow
> > > > 
> > > > On Sat, Oct 24, 2015 at 10:55 AM, casuistry <
> > > > notifications@github.com>
> > > > wrote:
> > > > 
> > > > > Ok, I'll see if I can check against the list with a filter
> > > > > 
> > > > > On Sat, Oct 24, 2015 at 10:48 AM, maxtheman33 <
> > > > > notifications@github.com>
> > > > > wrote:
> > > > > 
> > > > > > I was thinking second Sent from my BlackBerry 10 smartphone.
> > > > > > From:
> > > > > > casuistrySent: Saturday, October 24, 2015 10:13 AMTo:
> > > > > > casuistry/iemlReply
> > > > > > To: casuistry/iemlCc: maxtheman33Subject: Re: [ieml] Table - UI -
> > > > > > french
> > > > > > and english (#44)To get FR/EN to display on the table we have
> > > > > > these
> > > > > > options:
> > > > > > - get java cloud to make calls to DB and fill out the JSON before
> > > > > >   returning
> > > > > >   to the browser,
> > > > > > - browser makes calls (or cross-ckecks agains the list it already
> > > > > >   has)
> > > > > >   to
> > > > > >   DB when JSON is returned from java cloud and it updates JSON
> > > > > > - leave as is now but trigger an async call to fill out cells
> > > > > > 
> > > > > > Any other options?
> > > > > > 
> > > > > > On Thu, Oct 22, 2015 at 10:03 PM, maxtheman33 <
> > > > > > notifications@github.com>
> > > > > > wrote:
> > > > > > 
> > > > > > > do we have a way to tell that the cell in the table already
> > > > > > > has a
> > > > > > > record
> > > > > > > in
> > > > > > > ieml table in this case we can make it uneditable for now or
> > > > > > > may
> > > > > > > pop
> > > > > > > up
> > > > > > > edit screen.
> > > > > > > 
> > > > > > > On Thu, Oct 22, 2015 at 10:00 PM, casuistry <
> > > > > > > notifications@github.com>
> > > > > > > wrote:
> > > > > > > 
> > > > > > > > you beat me to it
> > > > > > > > 
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > <
> > > > > > > > https://github.com/casuistry/ieml/issues/44#issuecomment-150410587
> > > > > > > > .
> > > > > > > 
> > > > > > > ## 
> > > > > > > 
> > > > > > > Слава Украине! Glory to Ukraine!
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > > > > > > https://github.com/casuistry/ieml/issues/44#issuecomment-150410906
> > > > > > > .
> > > > > > 
> > > > > > —Reply to this email directly or view it on GitHub.
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > > > > https://github.com/casuistry/ieml/issues/44#issuecomment-150823933
> > > > > > .
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > > > https://github.com/casuistry/ieml/issues/44#issuecomment-150824207
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Слава Украине! Glory to Ukraine!
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/casuistry/ieml/issues/44#issuecomment-150825624
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/casuistry/ieml/issues/44#issuecomment-150825808.
> > 
> > ## 
> > 
> > Слава Украине! Glory to Ukraine!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/casuistry/ieml/issues/44#issuecomment-150825976.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/44#issuecomment-150826169.

## 

Слава Украине! Glory to Ukraine!

**Comment by casuistry** [comment]
yes

**Comment by casuistry** [comment]
correction: just putting the plumbing from the java side now

**Comment by casuistry** [comment]
Just pushed. You need to update java cloud. Also note that I have done
limited testing only.

**Comment by maxtheman33** [comment]
check it out, Now we can add actions to toaster as EDIT and PROMOTE we just set IEML to edit on the SharedProps and open corresponding view.

**Comment by casuistry** [comment]
Closing this issue and opening more focused issues.
