### ISSUE TITLE
Toast 2

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#49]
When user hits the button in toast, trigger create or update workflow

**Comment by maxtheman33** [comment]
done. Requires full retest of CRUD including cancelling actions.

**Comment by casuistry** [comment]
Looks good! Is it possible to see English as well? Only French shows.

**Comment by maxtheman33** [comment]
```
                                                                                  Screenshot?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: casuistrySent: Sunday, October 25, 2015 6:45 PMTo: casuistry/iemlReply To: casuistry/iemlCc: maxtheman33Subject: Re: [ieml] Toast 2 (#49)Looks good! Is it possible to see English as well? Only French shows.
```

—Reply to this email directly or view it on GitHub.

**Comment by casuistry** [comment]
I only see fr: .... then I have to use the scroll bars to scroll down to
see the buttons.
Screenshot won't help.

**Comment by maxtheman33** [comment]
```
                                                                                  I will see how to make toaster wider                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: casuistrySent: Sunday, October 25, 2015 7:17 PMTo: casuistry/iemlReply To: casuistry/iemlCc: maxtheman33Subject: Re: [ieml] Toast 2 (#49)I only see fr: .... then I have to use the scroll bars to scroll down to
```

see the buttons.
Screenshot won't help.

On Sun, Oct 25, 2015 at 6:47 PM, maxtheman33 notifications@github.com
wrote:

> Screenshot? Sent from my BlackBerry 10 smartphone. From: casuistrySent:
> Sunday, October 25, 2015 6:45 PMTo: casuistry/iemlReply To:
> casuistry/iemlCc: maxtheman33Subject: Re: [ieml] Toast 2 (#49)Looks good!
> Is it possible to see English as well? Only French shows.
> 
> —Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/49#issuecomment-150981201.

—Reply to this email directly or view it on GitHub.

**Comment by casuistry** [comment]
width is ok: text just wraps.

it is the height that is the issue. Browsing the web, maybe this could help:
https://github.com/angular/material/issues/3622

**Comment by maxtheman33** [comment]
it wraps because it is too narrow. We can clip it but that is not going to
look good. another option is to have horizontal scroll.

On Sun, Oct 25, 2015 at 7:31 PM, casuistry notifications@github.com wrote:

> width is ok: text just wraps.
> 
> it is the height that is the issue. Browsing the web, maybe this could
> help:
> https://github.com/angular/material/issues/3622
> 
> On Sun, Oct 25, 2015 at 7:24 PM, maxtheman33 notifications@github.com
> wrote:
> 
> > I will see how to make toaster wider
> > Sent from my BlackBerry 10 smartphone. From: casuistrySent: Sunday,
> > October
> > 25, 2015 7:17 PMTo: casuistry/iemlReply To: casuistry/iemlCc:
> > maxtheman33Subject: Re: [ieml] Toast 2 (#49)I only see fr: .... then I
> > have
> > to use the scroll bars to scroll down to
> > see the buttons.
> > Screenshot won't help.
> > 
> > On Sun, Oct 25, 2015 at 6:47 PM, maxtheman33 notifications@github.com
> > wrote:
> > 
> > > Screenshot? Sent from my BlackBerry 10 smartphone. From: casuistrySent:
> > > Sunday, October 25, 2015 6:45 PMTo: casuistry/iemlReply To:
> > > casuistry/iemlCc: maxtheman33Subject: Re: [ieml] Toast 2 (#49)Looks
> > > good!
> > > Is it possible to see English as well? Only French shows.
> > > 
> > > —Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/casuistry/ieml/issues/49#issuecomment-150981201.
> > 
> > —Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/casuistry/ieml/issues/49#issuecomment-150986948.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/49#issuecomment-150987271.

## 

Слава Украине! Glory to Ukraine!

**Comment by casuistry** [comment]
we cannot clip it! I am already clipping the text in the table.
