### ISSUE TITLE
If interacting with table, some routes work from bad initial state

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#51]
Workflow:
- From initial scree, navigate to e.g. M:O:.j.- and select table view.
- click on any non-empty cell
- select either create or update
- hit cancel

We can now have two different issues:

A) if user hits "Browser Back Arrow"
B) if user hits cancel again

We seem to be stuck in some kind of evil loop.
In some cases, when hitting "+", editor is prefilled with previous ieml string 

In A)
- after we hit the Browser Back, we end up in IEML editing page
- when cancel, we end up in M:O:.j.- editing page
- when browser back, we end up in M:O:.j.- editing page

In B)
- after the cancel we are in List screen
- click on "+" to add new ieml
- hit cancel
- we see the M:O:.j.- table

**Comment by maxtheman33** [comment]
how important is to have back button support? 
We will have to review/redesign all routes ensuring that all parameters are passed strictly as a part if URL. Only then browser buttons will work.
Right now, we pass params (ieml to edit) by setting then on shared services that explains the behaviour

something along these lines http://blog.falafel.com/fixing-back-button-simple-spa-behavior-using-location-hash/
.

**Comment by maxtheman33** [comment]
good considerations http://baymard.com/blog/back-button-expectations

**Comment by casuistry** [comment]
```
                                                                                  We can live without back button support, but using cancel also has issues.                                                                                                                                                                                                                                                                                                                                        Best regards,Andrew                                                                                                                                                                                                                From: maxtheman33Sent: Friday, October 30, 2015 9:57 PMTo: casuistry/iemlReply To: casuistry/iemlCc: casuistrySubject: Re: [ieml] If interacting with table, some routes work from bad initial state (#51)how important is to have back button support? 
```

We will have to review/redesign all routes ensuring that all parameters are passed strictly as a part if URL. Only then browser buttons will work.
Right now, we pass params (ieml to edit) by setting then on shared services that explains the behaviour

something along these lines http://blog.falafel.com/fixing-back-button-simple-spa-behavior-using-location-hash/
.

—Reply to this email directly or view it on GitHub.

**Comment by maxtheman33** [comment]
then what is left is this:

In B)

after the cancel we are in List screen
click on "+" to add new ieml
hit cancel
we see the M:O:.j.- table

**Comment by maxtheman33** [comment]
fixed B)

**Comment by casuistry** [comment]
Will refactor routing as another issue
