### ISSUE TITLE
Displaying tables should be REST accessible

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#56]
Currently we navigate to the table page through 

else {
    var toBeEdited = $scope.List[index];
    sharedProperties.setIemlEntry(toBeEdited)
    var earl = '/dicEdit/';
    $location.path(earl);  
}

We can leave this for the time being (or refactor if easier), but there should also be a path where the input to generate table is supplied as part of the address.

**Comment by maxtheman33** [comment]
what will serve as a key , if it is ieml - is it guaranteed to be URL-
safe?

On Tue, Nov 3, 2015 at 7:13 PM, casuistry notifications@github.com wrote:

> Assigned #56 https://github.com/casuistry/ieml/issues/56 to @maxtheman33
> https://github.com/maxtheman33.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/56#event-453869442.

## 

Слава Украине! Glory to Ukraine!

**Comment by casuistry** [comment]
I think it would be similar to what is done to validate ieml against the
parser.

**Comment by maxtheman33** [comment]
verify
