### ISSUE TITLE
Allow for annotations 

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#57]
We should allow users to CRUD annotations specific to generated tables.

Annotations can have hyperlinks which, when clicked, can get you to a different website.

Annotations are stored in DB

When table page is displayed, existing annotations should be read from DB and shown

As an example, we could have another tab, next to Table/Graph where a user can CRUD annotations. Basically a list that allows to add/remove (we don't need to update) items. Addition/deletion will have to trigger appropriate actions in the DB, using the input string (or uid) as the key. Chips could be a candidate for that.

DB format is as follows:

{IEML:"t.e.-m.u.-'",FR:"représentation dramatique",EN:"dramatic representation",PARADIGM:"0",LAYER:"3",CLASS:"4"}

Adding ANNOTATION:[ ] to that should be ok.

**Comment by maxtheman33** [comment]
```
                                                                                  It seems that what actually required is an ability to add freehand writing. Why it is an array then and not just long string?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: casuistrySent: Wednesday, November 4, 2015 7:45 PMTo: casuistry/iemlReply To: casuistry/iemlCc: maxtheman33Subject: [ieml] Allow for annotations  (#57)We should allow users to CRUD annotations specific to generated tables.
```

Annotations can have hyperlinks which, when clicked, can get you to a different website.

Annotations are stored in DB

When table page is displayed, existing annotations should be read from DB and shown

As an example, we could have another tab, next to Table/Graph where a user can CRUD annotations. Basically a list that allows to add/remove (we don't need to update) items. Addition/deletion will have to trigger appropriate actions in the DB, using the input string (or uid) as the key. Chips could be a candidate for that.

DB format is as follows:

{IEML:"t.e.-m.u.-'",FR:"représentation dramatique",EN:"dramatic representation",PARADIGM:"0",LAYER:"3",CLASS:"4"}

Adding ANNOTATION:[ ] to that should be ok.

—Reply to this email directly or view it on GitHub.

**Comment by casuistry** [comment]
```
                                                                                  User can add more than one annotation, and then decide to delete one of them. Array of strings seems more natural. I think this will most likely be used to store URLs.                                                                                                                                                                                                                                                                                                                                        Best regards,Andrew                                                                                                                                                                                                                From: maxtheman33Sent: Wednesday, November 4, 2015 7:53 PMTo: casuistry/iemlReply To: casuistry/iemlCc: casuistrySubject: Re: [ieml] Allow for annotations  (#57)                                                                                      It seems that what actually required is an ability to add freehand writing. Why it is an array then and not just long string?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: casuistrySent: Wednesday, November 4, 2015 7:45 PMTo: casuistry/iemlReply To: casuistry/iemlCc: maxtheman33Subject: [ieml] Allow for annotations  (#57)We should allow users to CRUD annotations specific to generated tables.
```

Annotations can have hyperlinks which, when clicked, can get you to a different website.

Annotations are stored in DB

When table page is displayed, existing annotations should be read from DB and shown

As an example, we could have another tab, next to Table/Graph where a user can CRUD annotations. Basically a list that allows to add/remove (we don't need to update) items. Addition/deletion will have to trigger appropriate actions in the DB, using the input string (or uid) as the key. Chips could be a candidate for that.

DB format is as follows:

{IEML:"t.e.-m.u.-'",FR:"représentation dramatique",EN:"dramatic representation",PARADIGM:"0",LAYER:"3",CLASS:"4"}

Adding ANNOTATION:[ ] to that should be ok.

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

**Comment by maxtheman33** [comment]
create separate collection for them?

**Comment by casuistry** [comment]
```
                                                                                  Ok, but If the ieml item is deleted, its annotations should be deleted as well.                                                                                                                                                                                                                                                                                                                                        Best regards,Andrew                                                                                                                                                                                                                From: maxtheman33Sent: Wednesday, November 4, 2015 8:06 PMTo: casuistry/iemlReply To: casuistry/iemlCc: casuistrySubject: Re: [ieml] Allow for annotations  (#57)create separate collection for them?
```

—Reply to this email directly or view it on GitHub.

**Comment by maxtheman33** [comment]
sure, there is a common key - ieml value

**Comment by maxtheman33** [comment]
checkout branch 'annotations'

NOTE: I forget to uncomment tree and table but you can use new TAGS tab anyway.

If you type in a http link it will be converted to hyperlink automatically. Nothing is persisted, unless you switch from TAGS tab to another tab. Optionally we can add 'save' button somewhere.

**Comment by maxtheman33** [comment]
pushing fixed $sec and uncommented . What needs to be done is perhaps some prompt to save changes when navigating away?

**Comment by casuistry** [comment]
I think it is straight-forward: write your annotation and hit "Enter".
Merge to master!
