### ISSUE TITLE
Batch tool to populate relations collection

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#61]

**Comment by casuistry** [comment]
iterate for each term, generate relations. For each child in relation, check if it exists in DB and persist that info.

(relation_name, parent, child, exists, displayed=true_by_default)

**Comment by casuistry** [comment]
Collection called definitions in db3

**Comment by maxtheman33** [comment]
```
                                                                                  Deciding whether to make it a nodejs or java with subsequent loading of json into db. Nodejs requires less steps but I am not sure how to execute it from a command line on the cloud. Should be relatively easy : locate git repo there and then run node myapp.js. But I d try first before starting to implement.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: casuistrySent: Thursday, November 19, 2015 9:48 PMTo: casuistry/iemlReply To: casuistry/iemlSubject: Re: [ieml] Batch tool to populate relations collection (#61)Collection called definitions in db3
```

—Reply to this email directly or view it on GitHub.

**Comment by maxtheman33** [comment]
nodejs app is good. Can be executed from ~/app-root/repo once logged into app. Plan B can be to run script locally and then uploading result to the cloud.

**Comment by maxtheman33** [comment]
done

**Comment by maxtheman33** [comment]
See comments above for an answer to how to run scripts. You will need rhc tool installed then  'ssh -editor', after that navigate to the node.js code and run  script from command line

**Comment by maxtheman33** [comment]
@mnozin convert rels.js script to use async.js and run with no concurrency. Enhance error logging.

**Comment by maxtheman33** [comment]
loaded on the cloud with modified script. Error messages are there because majority of ieml does not have any rels generated by the parser. Here are total counts:
 Completed loading rels for 588 terms. 1921 did not have any rels. Total processe
d 2509
