### ISSUE TITLE
Update UI to add Definitions tab

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#62]
Ensure back button works

**Comment by casuistry** [comment]
display relations as hypelinks to other definition pages
if relation is not exist, show but hyperlink is disabled
if relation is not displayed, do not show it

**Comment by maxtheman33** [comment]
format for the definitions JSON returned by crud factory 
$scope.definitions = [
        {"reltype":"reltype1", "rellist":
            [{"ieml":"I:E:M:L","id":"xxxxxxxx","exists":false, "visible":true},
            {"ieml":"I:E:M:L","id":"xxxxxxxx","visible":true, "exists":true},
            {"ieml":"I:E:M:L","id":"xxxxxxxx","visible":true,  "exists":true}
            ]},
        {"reltype":"reltypeN", "rellist":
            [{"ieml":"I:E:M:L","id":"xxxxxxxx","visible":true,  "exists":true},
            {"ieml":"I:E:M:L","id":"xxxxxxxx","visible":false, "exists":true}
            ]}
        ];

**Comment by maxtheman33** [comment]
done first cut
