### ISSUE TITLE
Update Relations collections on CRUD

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#63]

**Comment by casuistry** [comment]
exists attribute

**Comment by maxtheman33** [comment]
done

**Comment by casuistry** [comment]
create - yes
delete - yes
update - working on it

**Comment by casuistry** [comment]
delete - if deleted ieml is a paradigm, delete all relations generated for that ieml

**Comment by maxtheman33** [comment]
does update is working now?

**Comment by casuistry** [comment]
new, delete and updated finalized
