### ISSUE TITLE
Enhance display of relations

### ISSUE THREAD

**Issue by casuistry** [casuistry/ieml#72]
Currently relations only show ieml. The display should show the ieml and its corresponding EN or FR

**Comment by maxtheman33** [comment]
aren't they already shown?[image: Inline image 1]

On Wed, Jan 6, 2016 at 7:25 PM, casuistry notifications@github.com wrote:

> Assigned #72 https://github.com/casuistry/ieml/issues/72 to @maxtheman33
> https://github.com/maxtheman33.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/72#event-507719582.

## 

Слава Украине! Glory to Ukraine!

**Comment by casuistry** [comment]
cannot see the image...

So under relations, if something is not greyed-out, it should show both
ieml and the corresponding FR/EN. Only the ieml could be hyperlinked (or
both, does not really matter).

**Comment by maxtheman33** [comment]
```
                                                                                  I can see that already in the table view. Descriptions are abbreviated                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: casuistrySent: Thursday, January 7, 2016 7:54 PMTo: casuistry/iemlReply To: casuistry/iemlCc: maxtheman33Subject: Re: [ieml] Enhance display of relations (#72)cannot see the image...
```

So under relations, if something is not greyed-out, it should show both
ieml and the corresponding FR/EN. Only the ieml could be hyperlinked (or
both, does not really matter).

On Thu, Jan 7, 2016 at 7:06 PM, maxtheman33 notifications@github.com
wrote:

> aren't they already shown?[image: Inline image 1]
> 
> On Wed, Jan 6, 2016 at 7:25 PM, casuistry notifications@github.com
> wrote:
> 
> > Assigned #72 https://github.com/casuistry/ieml/issues/72 to
> > @maxtheman33
> > https://github.com/maxtheman33.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/casuistry/ieml/issues/72#event-507719582.
> 
> ## 
> 
> Слава Украине! Glory to Ukraine!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/72#issuecomment-169845803.

—Reply to this email directly or view it on GitHub.

**Comment by casuistry** [comment]
```
                                                                                  Sorry, should have specified for the definitions view                                                                                                                                                                                                                                                                                                                                        Best regards,Andrew                                                                                                                                                                                                                From: maxtheman33Sent: Thursday, January 7, 2016 8:34 PMTo: casuistry/iemlReply To: casuistry/iemlCc: casuistrySubject: Re: [ieml] Enhance display of relations (#72)                                                                                      I can see that already in the table view. Descriptions are abbreviated                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: casuistrySent: Thursday, January 7, 2016 7:54 PMTo: casuistry/iemlReply To: casuistry/iemlCc: maxtheman33Subject: Re: [ieml] Enhance display of relations (#72)cannot see the image...
```

So under relations, if something is not greyed-out, it should show both
ieml and the corresponding FR/EN. Only the ieml could be hyperlinked (or
both, does not really matter).

On Thu, Jan 7, 2016 at 7:06 PM, maxtheman33 notifications@github.com
wrote:

> aren't they already shown?[image: Inline image 1]
> 
> On Wed, Jan 6, 2016 at 7:25 PM, casuistry notifications@github.com
> wrote:
> 
> > Assigned #72 https://github.com/casuistry/ieml/issues/72 to
> > @maxtheman33
> > https://github.com/maxtheman33.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/casuistry/ieml/issues/72#event-507719582.
> 
> ## 
> 
> Слава Украине! Glory to Ukraine!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/72#issuecomment-169845803.

—Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

**Comment by maxtheman33** [comment]
this will require stacking terms  vertically , I am assuming that is OK

On Thu, Jan 7, 2016 at 8:35 PM, casuistry notifications@github.com wrote:

> Sorry, should have specified for the definitions view Best regards,Andrew
> From: maxtheman33Sent: Thursday, January 7, 2016 8:34 PMTo:
> casuistry/iemlReply To: casuistry/iemlCc: casuistrySubject: Re: [ieml]
> Enhance display of relations (#72) I can see that already in the table
> view. Descriptions are abbreviated Sent from my BlackBerry 10 smartphone.
> From: casuistrySent: Thursday, January 7, 2016 7:54 PMTo:
> casuistry/iemlReply To: casuistry/iemlCc: maxtheman33Subject: Re: [ieml]
> Enhance display of relations (#72)cannot see the image...
> 
> So under relations, if something is not greyed-out, it should show both
> ieml and the corresponding FR/EN. Only the ieml could be hyperlinked (or
> both, does not really matter).
> 
> On Thu, Jan 7, 2016 at 7:06 PM, maxtheman33 notifications@github.com
> wrote:
> 
> > aren't they already shown?[image: Inline image 1]
> > 
> > On Wed, Jan 6, 2016 at 7:25 PM, casuistry notifications@github.com
> > wrote:
> > 
> > > Assigned #72 https://github.com/casuistry/ieml/issues/72 to
> > > @maxtheman33
> > > https://github.com/maxtheman33.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/casuistry/ieml/issues/72#event-507719582.
> > 
> > ## 
> > 
> > Слава Украине! Glory to Ukraine!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/casuistry/ieml/issues/72#issuecomment-169845803.
> 
> —Reply to this email directly or view it on GitHub.
> 
> —Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/72#issuecomment-169861840.

## 

Слава Украине! Glory to Ukraine!

**Comment by casuistry** [comment]
```
                                                                                  Whatever fits. Some lists are long.                                                                                                                                                                                                                                                                                                                                        Best regards,Andrew                                                                                                                                                                                                                From: maxtheman33Sent: Thursday, January 7, 2016 8:39 PMTo: casuistry/iemlReply To: casuistry/iemlCc: casuistrySubject: Re: [ieml] Enhance display of relations (#72)this will require stacking terms  vertically , I am assuming that is OK
```

On Thu, Jan 7, 2016 at 8:35 PM, casuistry notifications@github.com wrote:

> Sorry, should have specified for the definitions view Best regards,Andrew
> From: maxtheman33Sent: Thursday, January 7, 2016 8:34 PMTo:
> casuistry/iemlReply To: casuistry/iemlCc: casuistrySubject: Re: [ieml]
> Enhance display of relations (#72) I can see that already in the table
> view. Descriptions are abbreviated Sent from my BlackBerry 10 smartphone.
> From: casuistrySent: Thursday, January 7, 2016 7:54 PMTo:
> casuistry/iemlReply To: casuistry/iemlCc: maxtheman33Subject: Re: [ieml]
> Enhance display of relations (#72)cannot see the image...
> 
> So under relations, if something is not greyed-out, it should show both
> ieml and the corresponding FR/EN. Only the ieml could be hyperlinked (or
> both, does not really matter).
> 
> On Thu, Jan 7, 2016 at 7:06 PM, maxtheman33 notifications@github.com
> wrote:
> 
> > aren't they already shown?[image: Inline image 1]
> > 
> > On Wed, Jan 6, 2016 at 7:25 PM, casuistry notifications@github.com
> > wrote:
> > 
> > > Assigned #72 https://github.com/casuistry/ieml/issues/72 to
> > > @maxtheman33
> > > https://github.com/maxtheman33.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/casuistry/ieml/issues/72#event-507719582.
> > 
> > ## 
> > 
> > Слава Украине! Glory to Ukraine!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/casuistry/ieml/issues/72#issuecomment-169845803.
> 
> —Reply to this email directly or view it on GitHub.
> 
> —Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/casuistry/ieml/issues/72#issuecomment-169861840.

## 

Слава Украине! Glory to Ukraine!

—Reply to this email directly or view it on GitHub.

**Comment by maxtheman33** [comment]
needs to be tested
